
package mx.gob.saludtlax.rh.wsdl.sifoficial;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * Somosby5Licence StartDate 2016-08-23 19:01:01.273
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consulta_tcode", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://opd2016.ddns.net:2280/test/ws/r/consulta_tcoded?WSDL")
public class ConsultaTcode extends Service {

    private final static URL CONSULTATCODE_WSDL_LOCATION;
    private final static WebServiceException CONSULTATCODE_EXCEPTION;
    private final static QName CONSULTATCODE_QNAME = new QName(
            "http://tempuri.org/", "consulta_tcode");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(
                    "http://opd2016.ddns.net:2280/test/ws/r/consulta_tcoded?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTATCODE_WSDL_LOCATION = url;
        CONSULTATCODE_EXCEPTION = e;
    }

    public ConsultaTcode() {
        super(__getWsdlLocation(), CONSULTATCODE_QNAME);
    }

    public ConsultaTcode(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTATCODE_QNAME, features);
    }

    public ConsultaTcode(URL wsdlLocation) {
        super(wsdlLocation, CONSULTATCODE_QNAME);
    }

    public ConsultaTcode(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTATCODE_QNAME, features);
    }

    public ConsultaTcode(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaTcode(URL wsdlLocation, QName serviceName,
            WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *         returns ConsultaTcodePortType
     */
    @WebEndpoint(name = "consulta_tcodePortType")
    public ConsultaTcodePortType getConsultaTcodePortType() {
        return super.getPort(
                new QName("http://tempuri.org/", "consulta_tcodePortType"),
                ConsultaTcodePortType.class);
    }

    /**
     *
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will
     *            have their default values.
     * @return
     *         returns ConsultaTcodePortType
     */
    @WebEndpoint(name = "consulta_tcodePortType")
    public ConsultaTcodePortType getConsultaTcodePortType(
            WebServiceFeature... features) {
        return super.getPort(
                new QName("http://tempuri.org/", "consulta_tcodePortType"),
                ConsultaTcodePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTATCODE_EXCEPTION != null) {
            throw CONSULTATCODE_EXCEPTION;
        }
        return CONSULTATCODE_WSDL_LOCATION;
    }

}
